apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labes:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: sailusha/mynginx:3.0
        ports:
        - containerPort: 80

